/*
 * Copyright (C) 2012  Krawler Information Systems Pvt Ltd
 * All rights reserved.
 * 
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
*/


package com.krawler.hql.accounting;
import com.krawler.common.admin.Company;
import com.krawler.common.admin.KWLCurrency;
import java.util.Date;
import java.util.Set;

public class BillingInvoice {
 private String ID;
    private String billingInvoiceNumber;
    private boolean autoGenerated;
    private String billTo;
    private String shipTo;
    private Date dueDate;
    private Date shipDate;
    private String memo;
    private Discount discount;
    private JournalEntry journalEntry;
    private Set<BillingInvoiceDetail> rows;
    private JournalEntryDetail customerEntry;
    private JournalEntryDetail shipEntry;
    private JournalEntryDetail otherEntry;
    private JournalEntryDetail creditorEntry;
    private JournalEntryDetail taxEntry;
    private ExchangeRateDetails exchangeRateDetail;
    private double externalCurrencyRate;
    private Company company;
    private KWLCurrency currency;
    private boolean deleted;
    private Tax tax;
    private Customer customer;
    private BillingInvoice parentInvoice;
    private RepeatedInvoices repeateInvoice;
    private String poRefNumber;

    public String getID() {
        return ID;
    }

    public void setID(String ID) {
        this.ID = ID;
    }

    public boolean isAutoGenerated() {
        return autoGenerated;
    }

    public void setAutoGenerated(boolean autoGenerated) {
        this.autoGenerated = autoGenerated;
    }

    public String getBillTo() {
        return billTo;
    }

    public void setBillTo(String billTo) {
        this.billTo = billTo;
    }

    public String getBillingInvoiceNumber() {
        return billingInvoiceNumber;
    }

    public void setBillingInvoiceNumber(String billingInvoiceNumber) {
        this.billingInvoiceNumber = billingInvoiceNumber;
    }

    public Company getCompany() {
        return company;
    }

    public void setCompany(Company company) {
        this.company = company;
    }

    public JournalEntryDetail getCustomerEntry() {
        return customerEntry;
    }

    public void setCustomerEntry(JournalEntryDetail customerEntry) {
        this.customerEntry = customerEntry;
    }
    public boolean isDeleted() {
        return deleted;
    }

    public void setDeleted(boolean deleted) {
        this.deleted = deleted;
    }

    public Discount getDiscount() {
        return discount;
    }

    public void setDiscount(Discount discount) {
        this.discount = discount;
    }

    public Date getDueDate() {
        return dueDate;
    }

    public void setDueDate(Date dueDate) {
        this.dueDate = dueDate;
    }

    public JournalEntry getJournalEntry() {
        return journalEntry;
    }

    public void setJournalEntry(JournalEntry journalEntry) {
        this.journalEntry = journalEntry;
    }

    public String getMemo() {
        return memo;
    }

    public void setMemo(String memo) {
        this.memo = memo;
    }

    public JournalEntryDetail getOtherEntry() {
        return otherEntry;
    }

    public void setOtherEntry(JournalEntryDetail otherEntry) {
        this.otherEntry = otherEntry;
    }

    public Set<BillingInvoiceDetail> getRows() {
        return rows;
    }

    public void setRows(Set<BillingInvoiceDetail> rows) {
        this.rows = rows;
    }

    public Date getShipDate() {
        return shipDate;
    }

    public void setShipDate(Date shipDate) {
        this.shipDate = shipDate;
    }

    public JournalEntryDetail getShipEntry() {
        return shipEntry;
    }

    public void setShipEntry(JournalEntryDetail shipEntry) {
        this.shipEntry = shipEntry;
    }

    public JournalEntryDetail getCreditorEntry() {
        return creditorEntry;
    }

    public void setCreditorEntry(JournalEntryDetail creditorEntry) {
        this.creditorEntry = creditorEntry;
    }

    public String getShipTo() {
        return shipTo;
    }

    public void setShipTo(String shipTo) {
        this.shipTo = shipTo;
    }

    public Tax getTax() {
        return tax;
    }

    public void setTax(Tax tax) {
        this.tax = tax;
    }

    public JournalEntryDetail getTaxEntry() {
        return taxEntry;
    }

    public void setTaxEntry(JournalEntryDetail taxEntry) {
        this.taxEntry = taxEntry;
    }

    public KWLCurrency getCurrency() {
        return currency;
    }

    public void setCurrency(KWLCurrency currency) {
        this.currency = currency;
    }

    public ExchangeRateDetails getExchangeRateDetail() {
        return exchangeRateDetail;
    }

    public void setExchangeRateDetail(ExchangeRateDetails exchangeRateDetail) {
        this.exchangeRateDetail = exchangeRateDetail;
    }

    public double getExternalCurrencyRate() {
        return externalCurrencyRate;
    }

    public void setExternalCurrencyRate(double externalCurrencyRate) {
        this.externalCurrencyRate = externalCurrencyRate;
    }

    public Customer getCustomer() {
        return customer;
    }

    public void setCustomer(Customer customer) {
        this.customer = customer;
    }

    public BillingInvoice getParentInvoice() {
        return parentInvoice;
    }

    public void setParentInvoice(BillingInvoice parentInvoice) {
        this.parentInvoice = parentInvoice;
    }

    public RepeatedInvoices getRepeateInvoice() {
        return repeateInvoice;
    }

    public void setRepeateInvoice(RepeatedInvoices repeateInvoice) {
        this.repeateInvoice = repeateInvoice;
    }

    public String getPoRefNumber() {
        return poRefNumber;
    }

    public void setPoRefNumber(String poRefNumber) {
        this.poRefNumber = poRefNumber;
    }
    
}
